version: '3.7'

services:
  server:
    image: klakegg/hugo:ext
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    env_file:
      - .env

  build:
    image: klakegg/hugo:ext
    volumes:
      - ".:/src"

  zscaler:
    build:
      context: .
      dockerfile: Dockerfile
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    env_file:
      - .env