version: '3.7'

services:
  server:
    image: klakegg/hugo:ext
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    env_file:
      - .env

  build:
    image: klakegg/hugo:ext
    volumes:
      - ".:/src"

  zscaler:
    build: ./docker/hugo
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    env_file:
      - .env

  pull_data:
    build: ./docker/js
    working_dir: /src
    command: npm run getData:loc
    volumes:
      - ".:/src"
    env_file:
      - .env