version: '3.7'

services:
  server:
    image: klakegg/hugo:ext
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"

  build:
    image: klakegg/hugo:ext
    volumes:
      - ".:/src"
