version: '3.8'

services:
  server:
    image: hugomods/hugo:exts
    command: hugo server --bind 0.0.0.0
    volumes:
      - .:/src
    ports:
      - "1314:1313"
    env_file:
      - .env

  build:
    image: hugomods/hugo:exts
    command: hugo --gc
    volumes:
      - ".:/src"
    env_file: 
      - .env

  pull_data:
    build: ./docker/js
    working_dir: /src
    command: npm run getData:loc
    volumes:
      - ".:/src"
    environment:
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.crt
    env_file:
      - .env